#!/usr/bin/env python3
"""Build the manuscript table for the three-mesh P418 CHT comparison."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


METRIC_LABELS = {
    "pressure_drop_Pa": r"Pressure drop",
    "outlet_temperature_change_K": r"Outlet temperature rise",
    "solid_maximum_temperature_change_K": r"Maximum solid-temperature change",
    "cooling_wall_heat_fraction": r"Signed wall heat / generated power",
}

STATUS_LABELS = {
    "monotonic_gci_reported": "monotonic",
    "identical_within_float64_resolution": "identical",
    "fine_pair_identical": "fine pair identical",
    "oscillatory_no_gci_reported": "oscillatory",
    "zero_crossing_no_gci_reported": "near-zero sign change",
    "apparent_order_not_resolved_no_gci_reported": "order unresolved",
}


def finite(value: object, label: str) -> float:
    number = float(value)
    if not math.isfinite(number):
        raise ValueError(f"{label} is not finite")
    return number


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-summary", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    payload = json.loads(args.input_summary.resolve().read_text(encoding="utf-8"))
    if payload.get("status") != "completed_three_mesh_p418_cht_comparison":
        raise ValueError("three-mesh P418 comparison is incomplete")
    levels = payload.get("mesh_levels")
    if not isinstance(levels, list) or [row.get("mesh_level") for row in levels] != [
        "coarse",
        "medium",
        "fine",
    ]:
        raise ValueError("coarse, medium and fine mesh rows are required")
    gci_rows = payload.get("grid_convergence")
    if not isinstance(gci_rows, list):
        raise ValueError("mesh GCI results are missing")
    gci_by_metric = {str(row.get("metric")): row for row in gci_rows}
    if set(gci_by_metric) != set(METRIC_LABELS):
        raise ValueError("mesh GCI quantities are incomplete")

    lines = [
        "% Generated by code/build_hccb_p418_mesh_sensitivity_table.py",
        r"\begin{table*}[htbp]",
        r"\centering",
        r"\caption{Three-mesh sensitivity for the representative conjugate-heat-transfer condition. The equivalent cell size is $[(V_f+V_s)/(N_f+N_s)]^{1/3}$. Grid Convergence Index (GCI) values use the actual unequal refinement ratios and a safety factor of 1.25 \cite{celik2008gci}; no percentage GCI is reported for an oscillatory or unresolved sequence, or when the response crosses zero.}",
        r"\label{tab:mesh_sensitivity}",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{@{}lrrrrrrr@{}}",
        r"\toprule",
        r"Grid & $N$ & $h_{\rm eq}$ ($\mu$m) & $\phi$ & $\Delta p$ (Pa) & $\Delta T_{\rm out}$ (K) & $\Delta T_{s,\max}$ (K) & $Q_{\rm wall}/Q_{\rm gen}$ \\",
        r"\midrule",
    ]
    for row in levels:
        lines.append(
            f"{str(row['mesh_level']).capitalize()} & "
            f"{int(row['total_cells']):d} & "
            f"{1.0e6 * finite(row['equivalent_cell_size_m'], 'equivalent cell size'):.2f} & "
            f"{finite(row['cell_volume_porosity'], 'porosity'):.5f} & "
            f"{finite(row['pressure_drop_Pa'], 'pressure drop'):.4g} & "
            f"{finite(row['outlet_temperature_change_K'], 'outlet temperature rise'):.4g} & "
            f"{finite(row['solid_maximum_temperature_change_K'], 'solid temperature rise'):.4g} & "
            f"{finite(row['cooling_wall_heat_fraction'], 'wall heat fraction'):.4g} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"}",
            r"\par\vspace{0.5ex}",
            r"\resizebox{\textwidth}{!}{%",
            r"\begin{tabular}{@{}lrrr@{}}",
            r"\toprule",
            r"Quantity & Refinement behaviour & Observed order & Fine-grid GCI \\",
            r"\midrule",
        ]
    )
    for metric, label in METRIC_LABELS.items():
        row = gci_by_metric[metric]
        status = str(row.get("convergence_status"))
        if status not in STATUS_LABELS:
            raise ValueError(f"unknown mesh convergence status: {status}")
        values = [finite(level[metric], metric) for level in levels]
        crosses_zero = min(values) <= 0.0 <= max(values)
        if crosses_zero:
            status_text = "near-zero sign change"
            order_text = "--"
            gci_text = "--"
        else:
            status_text = STATUS_LABELS[status]
            order = row.get("observed_order")
            order_text = (
                "--" if order is None else f"{finite(order, 'observed order'):.3f}"
            )
            fraction = row.get("fine_gci_fraction")
            gci_text = (
                "--"
                if fraction is None
                else f"{100.0 * finite(fraction, 'fine GCI'):.3f}\\%"
            )
        lines.append(
            f"{label} & {status_text} & {order_text} & {gci_text} \\\\"
        )
    lines.extend(
        [r"\bottomrule", r"\end{tabular}", r"}", r"\end{table*}", ""]
    )

    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
