#!/usr/bin/env python3
"""Build the separate legacy P391 reference case.

The current P418 paper calculations are generated by
``build_hccb_dense_cht_p418_matrix.py``.  Keeping this older P391 route
separate prevents its P051--P055 conditions and published-G2 mesh description
from being mixed into the current local-domain 60+9+9 study.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "parameters/literature_parameter_manifest.csv"
NUMERICAL = ROOT / "parameters/apd006_tdem_numerical_design_provenance.csv"
HELIUM_PROPERTIES = ROOT / "results/apd006_hccb_openfoam_helium_property_table/physicalProperties"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rows(path: Path, key: str) -> dict[str, dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return {row[key]: row for row in csv.DictReader(handle)}


def foam_header(location: str, object_name: str, class_name: str) -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Version: 13
    \\  /    A nd           |
     \\/     M anipulation  |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    format      ascii;
    class       {class_name};
    location    \"{location}\";
    object      {object_name};
}}

"""


def parse_patches(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    boundary_list = re.search(r"(?s)\n\s*\d+\s*\n\s*\(\s*\n(.*)\n\s*\)\s*$", text)
    if not boundary_list:
        raise ValueError(f"cannot locate the OpenFOAM patch list in {path}")
    return re.findall(
        r"(?m)^\s*([A-Za-z][A-Za-z0-9_]*)\s*\n\s*\{",
        boundary_list.group(1),
    )


def boundary_entries(entries: dict[str, str]) -> str:
    return "\n".join(f"    {name}\n    {{\n{body}\n    }}" for name, body in entries.items())


def scalar_field(location: str, name: str, dimensions: str, value: float, entries: dict[str, str]) -> str:
    return foam_header(location, name, "volScalarField") + f"""dimensions      {dimensions};
internalField   uniform {value:.12g};
boundaryField
{{
{boundary_entries(entries)}
}}
// ************************************************************************* //
"""


def vector_field(location: str, name: str, value: tuple[float, float, float], entries: dict[str, str]) -> str:
    vector = f"({value[0]:.12g} {value[1]:.12g} {value[2]:.12g})"
    return foam_header(location, name, "volVectorField") + f"""dimensions      [0 1 -1 0 0 0 0];
internalField   uniform {vector};
boundaryField
{{
{boundary_entries(entries)}
}}
// ************************************************************************* //
"""


def parse_reference(value: str) -> dict[str, float]:
    return {key: float(number) for key, number in (item.split("=", 1) for item in value.split(";"))}


def p406_cp(value: str, temperature_k: float) -> float:
    match = re.fullmatch(
        r"Cp=\((-?[0-9.eE+-]+)\*T_C\^2\+([0-9.eE+-]+)\*T_C\+([0-9.eE+-]+)\)\*1000",
        value.replace(" ", ""),
    )
    if not match:
        raise ValueError(f"cannot parse P406: {value!r}")
    a, b, c = (float(item) for item in match.groups())
    temperature_c = temperature_k - 273.15
    return (a * temperature_c**2 + b * temperature_c + c) * 1000.0


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--case", type=Path, required=True)
    parser.add_argument(
        "--case-id",
        help="Deprecated. Current P418 cases use build_hccb_dense_cht_p418_matrix.py.",
    )
    parser.add_argument(
        "--contract-fixture",
        action="store_true",
        help="Allow a software-only mesh fixture; forbidden for physical case execution.",
    )
    parser.add_argument("--parallel-subdomains", type=int, default=1)
    parser.add_argument("--end-time", type=int, default=5000)
    parser.add_argument("--write-interval", type=int, default=500)
    args = parser.parse_args()
    if args.parallel_subdomains < 1:
        raise ValueError("parallel-subdomains must be positive")
    if args.end_time < 1 or args.write_interval < 1:
        raise ValueError("end-time and write-interval must be positive")
    if args.case_id:
        raise RuntimeError(
            "--case-id belongs to the retired P051--P055 route. Use "
            "build_hccb_dense_cht_p418_matrix.py for current P418 calculations."
        )
    case = args.case.resolve()
    mesh_audit_path = case / "mesh_audit_summary.json"
    mesh_audit = json.loads(mesh_audit_path.read_text(encoding="utf-8"))
    if mesh_audit.get("status") != "hccb_pore_resolved_openfoam_mesh_preflight_passed":
        raise RuntimeError("steady dictionaries require a passed mesh preflight")
    mesh_manifest = mesh_audit.get("case_manifest", {})
    mesh_controls = mesh_manifest.get("numerical_controls", {})
    if not args.contract_fixture:
        if mesh_controls.get("role") != "P405 mesh-count candidate" or mesh_controls.get("mesh_level") != "G2":
            raise RuntimeError(
                "physical steady dictionaries require a declared P405 G2 mesh-count candidate; "
                "smoke/preflight meshes are forbidden"
            )
        if int(mesh_controls.get("published_target_cell_count", -1)) != 6_670_000 or not math.isclose(
            float(mesh_controls.get("background_cells_per_particle_diameter", float("nan"))),
            1.0 / 0.099,
            rel_tol=1.0e-12,
        ):
            raise RuntimeError("declared G2 mesh does not retain the source-derived P405 resolution contract")
        if (
            int(mesh_controls.get("sphere_icosphere_subdivisions", -1)) != 3
            or int(mesh_controls.get("surface_refinement_level", -1)) != 1
        ):
            raise RuntimeError("declared G2 mesh does not retain the disclosed ND057 surface representation")

    physical = rows(MANIFEST, "parameter_id")
    numerical = rows(NUMERICAL, "design_id")
    required_physical = [
        "P051", "P052", "P053", "P054", "P055", "P070", "P071", "P092",
        "P388", "P389", "P391", "P392", "P403", "P406",
    ]
    if any(physical[item]["status"] != "extracted" for item in required_physical):
        raise RuntimeError("one or more active physical entries are not extracted")
    for item in ("ND048", "ND049", "ND050", "ND051", "ND053", "ND057"):
        if item not in numerical or not numerical[item]["admission_status"].startswith("admitted"):
            raise RuntimeError(f"missing admitted numerical control {item}")

    fluid_boundary_path = case / "constant/fluid/polyMesh/boundary"
    solid_boundary_path = case / "constant/solid/polyMesh/boundary"
    fluid_patches = parse_patches(fluid_boundary_path)
    solid_patches = parse_patches(solid_boundary_path)
    required_external = {"inlet", "outlet", "inletTemperatureWall", "coolingWall", "symmetryWalls"}
    if not required_external.issubset(fluid_patches):
        raise RuntimeError(f"fluid patches missing: {sorted(required_external.difference(fluid_patches))}")
    fluid_interfaces = [name for name in fluid_patches if "_to_" in name]
    solid_interfaces = [name for name in solid_patches if "_to_" in name]
    if not fluid_interfaces or not solid_interfaces:
        raise RuntimeError("coupled fluid-solid interface patches were not found")

    reference = parse_reference(physical["P391"]["value"])
    case_matrix_sha256 = None
    matrix_row = None
    inlet_temperature = reference["T_in"]
    inlet_velocity = reference["u_in"]
    outlet_pressure = float(physical["P054"]["value"]) * 1.0e6
    cooling_temperature = float(physical["P055"]["value"])
    heat_source = float(physical["P053"]["value"]) * 1.0e6
    solid_k = float(physical["P092"]["value"])
    solid_rho = float(physical["P403"]["value"])
    dictionary_cp = p406_cp(physical["P406"]["value"], inlet_temperature)

    u_entries: dict[str, str] = {}
    t_entries: dict[str, str] = {}
    prgh_entries: dict[str, str] = {}
    for patch in fluid_patches:
        if patch == "inlet":
            u_entries[patch] = f"        type fixedValue;\n        value uniform (0 0 {inlet_velocity:.12g});"
            t_entries[patch] = f"        type fixedValue;\n        value uniform {inlet_temperature:.12g};"
            prgh_entries[patch] = f"        type fixedFluxPressure;\n        value uniform {outlet_pressure:.12g};"
        elif patch == "outlet":
            u_entries[patch] = "        type pressureInletOutletVelocity;\n        value uniform (0 0 0);"
            t_entries[patch] = f"        type inletOutlet;\n        inletValue uniform {inlet_temperature:.12g};\n        value uniform {inlet_temperature:.12g};"
            prgh_entries[patch] = f"        type fixedValue;\n        value uniform {outlet_pressure:.12g};"
        elif patch == "symmetryWalls":
            u_entries[patch] = "        type symmetry;"
            t_entries[patch] = "        type symmetry;"
            prgh_entries[patch] = "        type symmetry;"
        elif patch == "inletTemperatureWall":
            u_entries[patch] = "        type noSlip;"
            t_entries[patch] = f"        type fixedValue;\n        value uniform {inlet_temperature:.12g};"
            prgh_entries[patch] = f"        type fixedFluxPressure;\n        value uniform {outlet_pressure:.12g};"
        elif patch == "coolingWall":
            u_entries[patch] = "        type noSlip;"
            t_entries[patch] = f"        type fixedValue;\n        value uniform {cooling_temperature:.12g};"
            prgh_entries[patch] = f"        type fixedFluxPressure;\n        value uniform {outlet_pressure:.12g};"
        elif patch in fluid_interfaces:
            u_entries[patch] = "        type noSlip;"
            t_entries[patch] = f"        type coupledTemperature;\n        value uniform {inlet_temperature:.12g};"
            prgh_entries[patch] = f"        type fixedFluxPressure;\n        value uniform {outlet_pressure:.12g};"
        else:
            raise RuntimeError(f"unclassified fluid patch {patch!r}")

    p_entries = {patch: f"        type calculated;\n        value uniform {outlet_pressure:.12g};" for patch in fluid_patches}
    solid_t_entries = {
        patch: (
            f"        type coupledTemperature;\n        value uniform {inlet_temperature:.12g};"
            if patch in solid_interfaces
            else "        type zeroGradient;"
        )
        for patch in solid_patches
    }
    write(case / "0/fluid/U", vector_field("0/fluid", "U", (0.0, 0.0, inlet_velocity), u_entries))
    write(case / "0/fluid/p", scalar_field("0/fluid", "p", "[1 -1 -2 0 0 0 0]", outlet_pressure, p_entries))
    write(case / "0/fluid/p_rgh", scalar_field("0/fluid", "p_rgh", "[1 -1 -2 0 0 0 0]", outlet_pressure, prgh_entries))
    write(case / "0/fluid/T", scalar_field("0/fluid", "T", "[0 0 0 1 0 0 0]", inlet_temperature, t_entries))
    write(case / "0/solid/T", scalar_field("0/solid", "T", "[0 0 0 1 0 0 0]", inlet_temperature, solid_t_entries))

    (case / "constant/fluid").mkdir(parents=True, exist_ok=True)
    shutil.copy2(HELIUM_PROPERTIES, case / "constant/fluid/physicalProperties")
    write(case / "constant/fluid/momentumTransport", foam_header("constant/fluid", "momentumTransport", "dictionary") + "simulationType laminar;\n")
    write(case / "constant/fluid/g", foam_header("constant/fluid", "g", "uniformDimensionedVectorField") + "dimensions [0 1 -2 0 0 0 0];\nvalue (0 0 0);\n")
    solid_properties = foam_header("constant/solid", "physicalProperties", "dictionary") + f"""thermoType
{{
    type heSolidThermo;
    mixture pureMixture;
    transport constIsoSolid;
    thermo eConst;
    equationOfState rhoConst;
    specie specie;
    energy sensibleInternalEnergy;
}}
mixture
{{
    specie {{ molWeight 1; }}
    equationOfState {{ rho {solid_rho:.12g}; }}
    transport {{ kappa {solid_k:.12g}; }}
    thermodynamics {{ hf 0; Cv {dictionary_cp:.12g}; }}
}}
"""
    write(case / "constant/solid/physicalProperties", solid_properties)
    write(case / "constant/solid/fvModels", foam_header("constant/solid", "fvModels", "dictionary") + f"""energySource
{{
    type heatSource;
    cellZone all;
    q {heat_source:.12g};
}}
""")

    control = foam_header("system", "controlDict", "dictionary") + f"""regionSolvers
{{
    fluid fluid;
    solid solid;
}}
startFrom startTime;
startTime 0;
stopAt endTime;
endTime {args.end_time};
deltaT 1;
writeControl timeStep;
writeInterval {args.write_interval};
purgeWrite 0;
writeFormat ascii;
writePrecision 6;
writeCompression off;
timeFormat general;
timePrecision 6;
runTimeModifiable true;
"""
    write(case / "system/controlDict", control)
    fluid_schemes = foam_header("system/fluid", "fvSchemes", "dictionary") + """ddtSchemes { default steadyState; }
gradSchemes { default Gauss linear; }
divSchemes
{
    default none;
    div(phi,U) Gauss upwind;
    div(phi,K) Gauss linear;
    div(phi,h) Gauss upwind;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes { default corrected; }
"""
    solid_schemes = foam_header("system/solid", "fvSchemes", "dictionary") + """ddtSchemes { default steadyState; }
gradSchemes { default Gauss linear; }
divSchemes { default none; }
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes { default corrected; }
"""
    write(case / "system/fluid/fvSchemes", fluid_schemes)
    write(case / "system/solid/fvSchemes", solid_schemes)
    fluid_solution = foam_header("system/fluid", "fvSolution", "dictionary") + """solvers
{
    p_rgh { solver GAMG; smoother DICGaussSeidel; tolerance 1e-7; relTol 0.01; }
    "(U|h)" { solver PBiCGStab; preconditioner DILU; tolerance 1e-7; relTol 0.01; }
}
PIMPLE
{
    momentumPredictor yes;
    nNonOrthogonalCorrectors 0;
    residualControl { U 1e-4; h 1e-4; }
}
relaxationFactors
{
    rho 1.0;
    p_rgh 0.7;
    U 0.3;
    h 0.7;
}
"""
    solid_solution = foam_header("system/solid", "fvSolution", "dictionary") + """solvers
{
    "e.*" { solver PCG; smoother GaussSeidel; preconditioner DIC; tolerance 1e-6; relTol 0; }
}
PIMPLE
{
    nNonOrthogonalCorrectors 0;
    residualControl { e 1e-4; }
}
"""
    write(case / "system/fluid/fvSolution", fluid_solution)
    write(case / "system/solid/fvSolution", solid_solution)
    write(case / "system/fvSolution", foam_header("system", "fvSolution", "dictionary") + "PIMPLE {}\n")
    functions = foam_header("system", "functions", "dictionary") + """inletMassFlow
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch inlet;
    operation sum;
    fields (phi);
}
outletMassFlow
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch outlet;
    operation sum;
    fields (phi);
}
inletEnthalpyFlow
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch inlet;
    operation sum;
    weightField phi;
    fields (h);
}
outletEnthalpyFlow
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch outlet;
    operation sum;
    weightField phi;
    fields (h);
}
inletPressure
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch inlet;
    operation areaAverage;
    fields (p);
}
outletPressure
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch outlet;
    operation areaAverage;
    fields (p);
}
inletTemperature
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch inlet;
    operation areaAverage;
    fields (T);
}
outletTemperature
{
    type surfaceFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region fluid;
    patch outlet;
    operation areaAverage;
    fields (T);
}
solidTemperatureMaximum
{
    type volFieldValue;
    libs ("libfieldFunctionObjects.so");
    log yes;
    writeFields false;
    region solid;
    cellZone all;
    operation max;
    fields (T);
}
writeThermoObjects
{
    type writeObjects;
    libs ("libutilityFunctionObjects.so");
    region fluid;
    objects (mu kappa h);
    writeControl writeTime;
}
#includeFunc wallHeatFlux(name=fluidWallHeatFlux,writeFields=false,region=fluid,log=yes)
#includeFunc wallHeatFlux(name=solidWallHeatFlux,writeFields=false,region=solid,log=yes)
    """
    write(case / "system/functions", functions)

    decompose = foam_header("system", "decomposeParDict", "dictionary") + f"""numberOfSubdomains {args.parallel_subdomains};
method scotch;
"""
    write(case / "system/decomposeParDict", decompose)

    allrun = case / "Allrun.steady"
    if args.parallel_subdomains == 1:
        run_command = "foamMultiRun > log.foamMultiRun.steady 2>&1\n"
    else:
        run_command = (
            "rm -rf processor*\n"
            "decomposePar -allRegions > log.decomposePar.steady 2>&1\n"
            f"mpirun -np {args.parallel_subdomains} foamMultiRun -parallel "
            "> log.foamMultiRun.steady 2>&1\n"
            "reconstructPar -allRegions -latestTime > log.reconstructPar.steady 2>&1\n"
        )
    allrun.write_text(
        "#!/bin/sh\nset -eu\ncd \"${0%/*}\"\n" + run_command,
        encoding="ascii",
    )
    allrun.chmod(0o755)
    payload = {
        "status": "hccb_pore_resolved_openfoam_steady_case_built",
        "case_id": args.case_id or "P391_contract_reference",
        "case_matrix_sha256": case_matrix_sha256,
        "case_matrix_row": matrix_row,
        "mesh_packing_seed": mesh_audit.get("case_manifest", {}).get("packing_seed"),
        "mesh_role": mesh_controls.get("role"),
        "mesh_level": mesh_controls.get("mesh_level"),
        "contract_fixture": args.contract_fixture,
        "parameter_ids": required_physical,
        "numerical_design_ids": ["ND048", "ND049", "ND050", "ND051", "ND053", "ND057"],
        "reference": {"u_in_m_s": inlet_velocity, "T_in_K": inlet_temperature, "p_out_Pa": outlet_pressure},
        "cooling_wall_temperature_K": cooling_temperature,
        "uniform_solid_heat_source_W_m3": heat_source,
        "solid_thermal_conductivity_W_m_K": solid_k,
        "solid_density_kg_m3": solid_rho,
        "steady_dictionary_Cv_J_kg_K": dictionary_cp,
        "steady_dictionary_Cv_derivation": "P406 evaluated at P391 T_in; mandatory software representation only",
        "parallel_subdomains": args.parallel_subdomains,
        "end_time": args.end_time,
        "steady_iteration_end": args.end_time,
        "solver_time_semantics": "steady_iteration_index",
        "physical_time_s": None,
        "write_interval": args.write_interval,
        "write_interval_semantics": "steady_iterations",
        "fluid_patches": fluid_patches,
        "solid_patches": solid_patches,
        "fluid_interface_patches": fluid_interfaces,
        "solid_interface_patches": solid_interfaces,
        "mesh_audit_sha256": sha256(mesh_audit_path),
        "helium_properties_sha256": sha256(HELIUM_PROPERTIES),
        "new_fitted_physical_parameters": [],
        "allowed_claim": "source-backed steady CHT solve configuration after a passed mesh preflight",
        "forbidden_claims": ["transient HCCB calibration", "Li2TiO3 transfer", "neural training truth"],
    }
    (case / "steady_case_manifest.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
